[build]
  publish = "./"
  functions = "functions"
  command = "npm install"
  
[dev]
  framework = "#custom"
  command = "npm run netlify-dev"
  targetPort = 8888
  port = 8080
  
# Serve static files in public folder directly
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/config.js"
  to = "/public/config.js"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Socket.io isteklerini kendi serverless fonksiyonumuza yönlendirme
[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server/socket.io/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 200
  
# Cache configuration for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
