[build]
  publish = "./"
  
# Serve static files in public folder directly
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/config.js"
  to = "/public/config.js"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "https://rock-paper-scissors.onrender.com/socket.io/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 200
  
# Cache configuration for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
