services:
<<<<<<< HEAD
  - type: web
    name: rock-paper-scissors
    runtime: static
=======
  - type: static_site
    name: rock-paper-scissors
>>>>>>> cfa106c1321b874ccb1c9ce62e8bb35c5cc98011
    envVars:
      - key: NODE_VERSION
        value: 16
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
